### ISSUE TITLE
Looking for "tcga_gtex_paired.rds"

### ISSUE THREAD

**Issue by nattzy94** [longfei8533/SDC#1]
Hi,

Thank you for making all your code and data available. I am trying to replicate the analysis but cannot find the following  file: `rawdata/toil/tcga_gtex_paired.rds`.

Is it possible to make this file available? Or perhaps to share what this contains/how it was generated?

**Comment by longfei8533** [comment]
> 
Hi,
The tcga_gtex_paired.rds file has been uploaded to rawdata/toil/ folder is available now.

**Comment by longfei8533** [comment]
> 
@nattzy94 
Hi,
The tcga_gtex_paired.rds file has been uploaded to rawdata/toil/ folder is available now. 


> Hi,
> 
> Thank you for making all your code and data available. I am trying to replicate the analysis but cannot find the following file: `rawdata/toil/tcga_gtex_paired.rds`.
> 
> Is it possible to make this file available? Or perhaps to share what this contains/how it was generated?

**Comment by nattzy94** [comment]
@longfei8533 , thanks so much!
